name: Update readme
on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-leetcode
    - name: Run update.py
      run: |
        python update.py
    - name: Commit changes
      run: |
        git config --local user.name 'jyp'
        git config --local user.email 'singiri129@jbnu.ac.kr'
        git add -A
        git commit -m "auto update README.md" || echo "No changes to commit"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PAToken }}  # 여기서 PAT는 위에서 설정한 secret 이름입니다
        branch: ${{ github.ref }}
