name: Update readme
on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-leetcode
    - name: Run update.py
      run: |
        python update.py
    - name: Commit and push changes
      run: |
        git config --local user.name 'jyp'
        git config --local user.email 'singiri129@jbnu.ac.kr'
        git add -A
        git commit -m "auto update README.md" || echo "No changes to commit"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.PATOKEN }}
